# TODO : dockerize 2 services => backend-server and worker-server
version: "3"
services:
  backend-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 8500:4000
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres-db
      - PGDATABASE=postgres
      - PGPASSWORD=messi99
      - PGPORT=5432
      - WORKER_SERVER_HOST=worker-server
      - WORKER_SERVER_PORT=4001
  worker-server:
    build:
      dockerfile: Dockerfile
      context: ./worker-server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
  redis-server:
    image: redis:latest
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: messi99
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 80:80
