apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker-server
  template:
    metadata:
      labels:
        component: worker-server
    spec:
      containers:
        - name: worker-server
          image: markamgad4/fib-worker-server:latest
          ports:
            - containerPort: 4001
          env:
            - name: REDIS_HOST
              value: redis-server-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
